### ISSUE TITLE
希望這項目可以更新flutter2空安全  新手想自己改 改的好吃力阿...

### ISSUE THREAD

**Issue by Timmyspfff** [ducafecat/flutter_learn_news#2]

**Comment by ducafecat** [comment]
https://github.com/ducafecat/flutter_ducafecat_news_getx

关注下这个新版本

**Comment by Timmyspfff** [comment]
> https://github.com/ducafecat/flutter_ducafecat_news_getx
> 
> 关注下这个新版本

謝謝大佬
